language: python
python:
  - '2.7'
env:
  - DJANGO_SETTINGS_MODULE=djangophotoapp.settings.test
install:
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install bower
script:
  - bower install --settings=djangophotoapp.settings.test
  - python djangophotoapp/manage.py collectstatic --noinput --settings=djangophotoapp.settings.test
  - coverage run --source photoapp djangophotoapp/manage.py test photoapp
after_success:
  - coveralls
deploy:
  provider: heroku
  buildpack:
    - node
    - python
  api_key:
    secure: r1I1/5j2yISohaa5Xf7N4I/uv24VCkuniUh0u/mI/4XQtvvPtWKs1RJRlpRn5psWwnB52Yr+b5QVU0z+J/1u0JKO/jMW6PrewQ7RoBiwdWCg/bYBoq1Yd/2ycykY2VN+cPLNJHERMJ+n7abzBpUmWb/f6qDnrFzrDUWDZfflNl/XJLy3GFeLcuFEvQOMJCU0lpCWzAqVL/vrkkuRTuuKTIPL+xRKxreRJEd6PreN+o2qYLM22XMQRZFd5xsi1CIV9RmTC78wUNIGKZ15ruIlfJoEZt/RvGVIyYHAxWawsasRn/w7lVOlbWPlBslmWO8CwxM6g1fD015ULbqS9RyxBlJSk1Hcn+TE94yUKXF3PlJ1TyUrawomMa1CeXq8uEjM3G973hTVlbYl1E2Jdyi2pf0v4NqwT8IHmhj5cEZ6LURvEBXCzYPhWeXmMp1yAPWViryuYuSFj/q05DiSWKKEWYIbbOIn5SQz+MSe24xrJFIE4nzGIC4mPDyFpfwwFNVt8lmLiLicVX5UzFm0RiPoMSjkW99Pd4PEmY2Zn6YWQ3pnsS1eBuqsSOuegnowkBmM59t6oUeKAfY4GHrll4E21nMRJDX6NHUzsCQrsXr2WjSoXAZnBnN0eCG1sYMVbMAstnrOWbGLe5sxSTaQILp+sFbQaEDCxa15E60+swZ9xNE=
  strategy: git
  app: myphotoapplication
  on:
    repo: andela-ooshodi/django-photo-application
after_deploy:
  - "heroku ps:scale web=1 --app myphotoapplication"